# Configurations
title:            ભગવદ્ ગીતા
longtitle:        પરમ પિતા પરમેશ્વર ની વાણી 
author:           ભાવેશ પ્રજાપતિ
email:            bhaveshp.magento@gmail.com
description: >
  જીવન જીવવા માટે ની માર્ગદર્શિકા એ પણ સ્વયં પૂર્ણ પુરષોતમ પરમેશ્વર ના મુખે.
version:          1.0
gitbook_version:  3.2.3

url:              'https://bhaveshpp.github.io/gita/'
baseurl:          '/gita'
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico
manifest_path:     /assets/manifest.json

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:title

exclude:
  - _drafts

collections:
  adhyay:
    output: true
    permalink: /:path
  ram:
    output: true
    permalink: /:path

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true
